#!/bin/sh
set -e

jq '.ExtensionInstallForcelist += ["jnofdoejfipgalklopidpdeofjebihcf;file://usr/share/chromium/extensions/msg-extname.crx"]' \
   /etc/chromium/policies/managed/extension_policy.json > /etc/chromium/policies/managed/extension_policy.json.tmp && \
mv /etc/chromium/policies/managed/extension_policy.json.tmp /etc/chromium/policies/managed/extension_policy.json

exit 0
